#use_frameworks!
inhibit_all_warnings!
target 'HeroArchitecture_Example' do
  pod 'HeroArchitecture', :path => '../'
  pod 'Realm'
  pod 'MBProgressHUD'

  target 'HeroArchitecture_Tests' do
    inherit! :search_paths

    
  end
end
